# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-15 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departnemnt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Acceptancerate', models.CharField(max_length=20)),
                ('TuitionFees', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='departnemnt',
            name='University',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.University'),
        ),
    ]
